# Image Color Compression — Preprocessing

In [19]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [21]:
import cv2

butterfly = cv2.imread("Dataset/butterfly.jpeg")
barnowl = cv2.imread("Dataset/barnowl.jpeg")

print(butterfly.shape, butterfly.dtype)
print(barnowl.shape, barnowl.dtype)

(529, 529, 3) uint8
(516, 387, 3) uint8


# 1. Reshape image → pixel matrix

In [23]:
import cv2
import numpy as np

butterfly_rgb = cv2.cvtColor(butterfly, cv2.COLOR_BGR2RGB)

shape = butterfly_rgb.shape

X = butterfly_rgb.reshape(-1, 3)

print("Pixel matrix:", X.shape)
print("Original image shape:", shape)
print("Value range:", X.min(), "-", X.max())
print("First 3 pixels:\n", X[:3])

Pixel matrix: (279841, 3)
Original image shape: (529, 529, 3)
Value range: 0 - 255
First 3 pixels:
 [[129 160  93]
 [129 160  93]
 [129 159  95]]


# 2. Pixel sampling for fast fitting

Fitting K-Means on all pixels every iteration is slow. We fit on a random 10,000-pixel sample and then assign all pixels to the learned centroids — a standard speed-up that barely changes the result because the colour distribution is dense.

In [26]:
rng = np.random.RandomState(42)
idx = rng.choice(len(X), 10000, replace=False)
X_fit = X[idx]
print('sample for fitting:', X_fit.shape)
print('full set to assign:', X.shape)

sample for fitting: (10000, 3)
full set to assign: (279841, 3)


# 3. Round-trip check (loss-less reshape)

Reshaping back to an image and comparing to the original must give MSE = 0 — proving the only information loss in this project comes from K-Means, not from the preprocessing.

In [28]:
restored = X.reshape(shape)

print("Restored shape:", restored.shape)

mse = np.mean((butterfly_rgb.astype(np.float32) - restored.astype(np.float32)) ** 2)

print("MSE vs original:", mse)

print("Identical:", np.array_equal(butterfly_rgb, restored))

Restored shape: (529, 529, 3)
MSE vs original: 0.0
Identical: True
